services:
  - type: web
    name: qltrading-web
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server/index.js"
    envVars:
      - key: PORT
        value: "3000"
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CACHE_TTL_MS
        value: "5000"
      - key: WHATSAPP_URL
        value: "https://wa.me/message/P6BBPSDL2CC4D1"
  - type: worker
    name: qltrading-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node bot/bot.js"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_TOKEN
        sync: false
